import Head from "next/head";
import '../components/common/ClientHeader/ClientHeader'
import ClientContainer from "../components/common/ClientContainer/ClientContainer";
import ClientHome from "../components/ClientHome/ClientHome";
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { Provider } from "react-redux";
import { store } from '../redux/app/store'

const Client = () => {

  return (
    <div lang="en">
      <Head>
        <title>Foody | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Provider store={store}>
          <ClientContainer>
            <ClientHome />
          </ClientContainer>
        </Provider>
      </>
    </div>
  );
};

export default Client;

export const getServerSideProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common']))
  }
});